---
- name: Quick group_vars via file in project testing
  hosts: all
  gather_facts: false
  tasks:
    - name: Show variable from group_vars file
      ansible.builtin.debug:
        var: hostvars[inventory_hostname].taco